# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py

conda:
  environment: environment.yml

build:
  os: ubuntu-lts-latest
  tools:
    python: miniconda-latest
  jobs:
    post_create_environment:
      - python -m pip install sphinx_rtd_theme

python:
  install:
   - method: pip
     path: .
