# https://travis-ci.org/dashboard
# https://config.travis-ci.com/explore

os: linux
dist: bionic
language: python
arch:
  - amd64
python:
  - '3.6'
  - '3.7'
  - '3.8'
branches:
install:
  - pip install netCDF4
  only:
  - master
script:
  - pwd
  - cd parsac/examples
  - ls
  - ls ../
#  - python -m ../parsac_run.py calibration run idealized.xml
