name: Build and test
on:
  push:
    branches:
    - "**"
  pull_request:
jobs:
   install_and_run:
      if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
      runs-on: "ubuntu-latest"
      defaults:
        run:
          shell: bash -el {0}
      steps:
      - name: Clone
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: parsac
      - run: pip install -v .
      - uses: actions/checkout@v4
        with:
          repository: 'gotm-model/code'
          ref: 'v6.0'
          path: 'gotm'
          submodules: 'recursive'
      - run: |
          conda install -c conda-forge fortran-compiler cmake netcdf-fortran
          cmake -S gotm -B gotm/build
          cmake --build gotm/build --target install
          cd examples
          export PATH="$PATH:$HOME/local/gotm/bin"
          python optimize_gotm.py